[
"Is this on?",
"Ah, Salaam and good evening to you worthy friend.",
"You ever feel small?",
"How do I look?",
"Solomon...",
"Nearly missed it!",
"Hey, O'Donnell, save some for the game.",
"There was me, that is Alex, and my three droogs, that is Pete, Georgie and Dim and we sat in the Korova milkbar trying to make up our rassoodocks what to do with the evening.",
"What are you doing, going behind my back?",
"Carrie!",
"Walter...time for school, honey.",
"What's that?",
"Stop!",
"Hey...",
"Snuggle in, sweetie.",
"Wow.",
"Where's the crash cart!?",
"He was delirious.",
"That's a funny one!",
"Legend tells of a legendary warrior whose Kung Fu skills were the stuff of legend.",
"The vision dims and all that remains are mememories.",
"So where are you?",
"We're under attack!",
"Mommy got sick and it happened just like that and there was nothing anybody would do.",
"This construction site is causing mortal and irreparable harm to an unsuspecting public!",
"Think of it, Thing.",
"When you hit Bangkok, there's really only one place to go.",
"Shit.",
"Freeze!",
"If anyone finds this, then I guess my plan didn't work and I'm already dead...",
"Edmund Get Away from there!",
"What are you looking at?",
"What kind is it?",
"Any word from Doug?",
"I'll tell you a tale of the bottomless blue.",
"It's getting cold.",
"Did you know there are more people with genius IQ’s living in China than there are people of any kind living in the United States?",
"The world of investing can be a jungle.",
"Choose life. Choose a job. Choose a career. Choose a family, Choose a fucking big television, Choose washing machines, cars, compact disc players, and electrical tin openers.",
"Come on, Son --this is no place for us.",
"I'd never given much thought to how I would die..",
"She isn't coming yet, Toto.",
"I had the most amazing dream last night.",
"You're doing it wrong.",
"People were always asking me, did I know Tyler Durden.",
"Moving to survey site B... closing on object four.",
"The time -- 7:15 A.M., WOR, New York.",
"Help! Someone help me!",
"I'm so worried for that boy.",
"Where are you?!",
"Intruder!",
"... but if we hesitate we'll lose this important source of dilithium.",
"Did you hear that?",
"We made it.",
"Command station, this is ST 321.",
"There isn't a droid made that can out fly you, Master, and no other way to get to the Chancellor . . .",
"Echo Three to Echo Seven.",
"This will begin to make things right.",
"Captain.",
"Hurry!",
"I say, this is outright rude of the man!",
"You don't do anything more.",
"Good morning.",
"Whoa, whoa, whoa... what's that?",
"We are here.",
"They arrived almost half a century ago.",
"Goddamn bugs.",
"Hello?",
"Hear me?",
"Houston, I can't get this thing to work...",
"The Tesseract has awakened.",
"Yeah. .'Cause he's an asshole.",
"Oh, hi.",
"High open space, exposed structural elements.",
"\"..when the three planets are in eclipse..\"",
"Explorer, please verify that the P1 ATA removal on replacement cap part 1 and 2 are complete.",
"Is he real?",
"Hey! Hey, baby, what’s going on here?",
" I have a theory about how this all started...",
"You have a choice in this world, I believe, about how to tell sad stories.",
"the leader in all forms of armament used by the United States Army.",
"...Rossen... Lieberman... Wachsberg...",
"Elsa. Psst. Elsa! Psst.",
"The chickens' heads jerk up toward the sound.",
"Frank, do you think you could give me a hand with these bags?",
"Oh my God, I got the most fucked up thing I been meanin' to tell you.",
"- and today it is right that we should ask ourselves the one most important question: What is the purpose of these years, the purpose for all this demanding work, the purpose for the sacrifices made those who love us?",
"Hi. I'm from out of town… on business from the U.S.",
"Left pocket.",
"Eager to mend its tarnished image, Los Angeles has really put out the welcome mat for tomorrow's summit.",
"Year after year, twenty-something women come to New York City in search of the two \"L's\": labels and love.",
"You Mongrel!",
"Do you know how long I've wanted this?",
"I don't know, dude.",
"I love you, too!",
"He wants you to turn, look in camera and say the lines.",
"Where are you going, Jelly Bean?",
"This is unbelievable - look at this.",
"\"Movietown News\" presents... Spotlight on Adventure!",
"Madman... Hideous spider... Run..."
].each do |w|
  word = Word.new
  word.line = w
  word.save
end
