# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 452983ae59108aca96f269701bb1cc547bfdd43722d057369611aa3559e444a5b2aa315797dca8f4b28b085060279130cb0db9d4263dd843d46def85fef543bf

test:
  secret_key_base: 8e60e6467c33e469deb7c7abddcce2e6d13b440adb4dca834ab8979036b5290dfd37ac97bb6ebed50aeffb6e71a9087f841bbe2c878c69684b11d8688c6ac6af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
