# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec40a7fb1d81260201d67dd9131935509e4580fb45371d39f09ab587de918578d06a84bf488ca72c18382fd41af662dc59f93c8d31e785f52f18afe624e428db

test:
  secret_key_base: 28a6733b5e6a1c10c28fb74916211cb76a0caf8b1534f85ca29867dc3a9d5bbb19b86c0ee3684146cb7c0c5c127bd7b1e161895d1b4c4507b687486ed6d40339

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
